blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
]

diary/usext/urls.py
# from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
	path('',  views.UserExtendsUpdate.as_view(), name='profile'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'', include('blog.urls')),
]

test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
]

diary/usext/models.py
from django.db import models
from django.contrib.auth.models import User

class UserExtends(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(null=True, blank=True, verbose_name='Аватарка')
	vip = models.DateTimeField(help_text='Дата по которую пользователь имеет ВИП-статус')

diary/usext/forms.py
from django.forms import ModelForm
from .models import UserExtends

class UserExtendsForm(ModelForm):

    class Meta:
        model = UserExtends
        fields = ['avatar']

    def __init__(self, def_img, *args, **kwargs):
        self.def_img = def_img
        super().__init__(*args, **kwargs)

diary/usext/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from .models import UserExtends
from django.urls import reverse_lazy
from diary.settings import DEFAULT_IMG_FOR_POST_BACKGROUND
from .forms import UserExtendsForm

class UserExtendsUpdate(LoginRequiredMixin,UpdateView):
	model = UserExtends
	form_class = UserExtendsForm
	success_url = reverse_lazy('profile')

	def get_object(self):
		obj = UserExtends.objects.get(user = self.request.user)
		return obj

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['def_img'] = DEFAULT_IMG_FOR_POST_BACKGROUND
		return kwargs

diary/usext/templates/usext/userextends_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

{% include "account/blocks/start_block.html" %}
<div class="section-title">
	<h2 class="title">{% trans 'Profile settings' %}</h2>
</div>
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="col-md-12">
		<div class="form-group common_center">
			{% if form.avatar.value.url|default_if_none:'clear' != 'clear'  %}  
			<label for="id_img">{% trans 'Текущая фоновое изображение' %}:</label>
			<img class="common_ava_height" id="id_img" src="{{ form.avatar.value.url|default_if_none:'clear' }}" alt="">

			<div class="file-upload">
				<label>
					<input type="file" name="avatar" id="id_avatar" class="file-input-id">
					<span>{% trans 'Выберите изображение' %}</span>
				</label>
			</div>

			<input type="checkbox" name="avatar-clear" id="avatar-clear_id">
			<label for="avatar-clear_id">{% trans 'Сбросить фоновую картинку' %}</label>
			{% else %}
			<label for="id_img">{% trans 'Текущая фоновое изображение' %}:</label><br>
			<img class="common_ava_height" id="id_img" src="{{ form.def_img }}" alt="">

			<div class="file-upload">
				<label>
					<input type="file" name="avatar" id="id_avatar" class="file-input-id">
					<span>{% trans 'Выберите изображение' %}</span>
				</label>
			</div>

			{% endif %}

		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group common_center">
			<button class="primary-button">{% trans 'Сохранить пост' %}</button>
		</div>
	</div>  
</form>




{% include "account/blocks/end_block.html" %}
{% endblock %}

{% block js %} 
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script type="text/javascript">
	function previewFile() {
		var preview = document.getElementById('id_img');
		var file    = document.getElementById('id_avatar').files[0];
		var reader  = new FileReader();

		reader.onloadend = function () {
			preview.src = reader.result;
		}

		if (file) {
			reader.readAsDataURL(file);
		}
	}


	$(document).ready( function() {
		$("#id_avatar").change(function(){
			previewFile()
		});
	});
</script>
{% endblock %}