blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
]

diary/blog/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


urlpatterns = [
	path('', views.index, name='index'),
	url(r'^permission-denied/$', views.perm_denied, name='perm-denied'),
	url(r'^ps/$', views.PostListView.as_view(), name='posts'),
	url(r'^p/(?P<pk>[-\w]+)$', views.PostDetailView.as_view(), name='post-detail'),
]

urlpatterns += [  
    url(r'^p/add/$', views.PostCreate.as_view(), name='post_create'),
    url(r'^p/(?P<pk>[-\w]+)/update/$', views.user_permitted(views.PostUpdate.as_view()), name='post_update'),
    url(r'^p/(?P<pk>[-\w]+)/delete/$', views.user_permitted(views.PostDelete.as_view()), name='post_delete'),
    url(r'^t/(?P<tag>[-\w]+)/$', views.search_by_tag, name='tag_search'),
    url(r'^search/$', views.search, name='tag_search_form'),
   ]

mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
]

test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
]

diary/blog/models.py
from django.db import models
from django.urls import reverse
# from authentication.models import Account
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase
import uuid 
from diary.settings import DEFAULT_IMG_FOR_POST_BACKGROUND
from usext.models import UserExtends

class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    # tag = models.ForeignKey(GenericUUIDTaggedItemBase, related_name="uuid_tagged_items", on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Уникальный ИД для поста')
    text = models.TextField(max_length=4000, help_text='Введите текст', null=False, blank=False)
    post_date = models.DateTimeField(auto_now_add=True, help_text='Дата публикации')
    modify_date = models.DateTimeField(auto_now=True, help_text='Дата редактирования')
    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE, blank=False)
    tags = TaggableManager(through=UUIDTaggedItem,blank=True)
    CURRENT_STATUS = (
        ('d', 'Deleted'),
        ('a', 'Active'),
        ('h', 'Hidden'),
        ('b', 'Banned'),
    )

    status = models.CharField(max_length=1, choices=CURRENT_STATUS, blank=True, default='a', help_text='Статус поста')

    class Meta:
    	ordering = ['-post_date']

    def __str__(self):

    	return "%s (%s)" % (self.id,self.post_date)

    def get_absolute_url(self):

        return reverse('post-detail', args=[str(self.id)])

    @property
    def get_post_bg(self):
        user_data = UserExtends.objects.get(user = self.user)
        if user_data.avatar is None or user_data.avatar == '':
            image_url = DEFAULT_IMG_FOR_POST_BACKGROUND
        else:
            image_url = user_data.avatar.url
        return image_url



class PostImages(models.Model):
    image = models.ImageField(blank=False)
    post = models.ForeignKey('Post',on_delete=models.CASCADE)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order',]

mysite/blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

diary/blog/forms.py
from django.forms import ModelForm, inlineformset_factory
from .models import Post, PostImages
import re
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from diary.settings import USEXT_TEXT_LENGTH_COMMON, USEXT_FILES_COUNT_VIP, USEXT_FILES_COUNT_COMMON,USEXT_TEXT_LENGTH_VIP
from django.db.models import Count

litnum_re = re.compile(r"^\w+$")

class PostImagesForm(ModelForm):
    
    class Meta:
        model = PostImages
        fields = ['image','order']



class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['text','tags']

    def __init__(self, vip, maxsymb, *args, **kwargs):
        self.vip = vip
        self.maxsymb = maxsymb
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(PostForm, self).clean()
        cleaned_tags = cleaned_data.get("tags")
        cleaned_text = cleaned_data.get("text")
        # cleaned_files = cleaned_data.get("files")
        # print('/'*80)
        # print(cleaned_files)
        if self.vip < timezone.now() and len(cleaned_text) > USEXT_TEXT_LENGTH_COMMON:
            raise forms.ValidationError("Пост длинее 400 символов доступен только ВИП пользователям.")
        elif self.vip >= timezone.now() and len(cleaned_text) > USEXT_TEXT_LENGTH_VIP:
            raise forms.ValidationError("Пост должен быть менее 4000 символов.")

        tag_count = 0
        for tag in cleaned_tags:
            tag_count +=1
            if tag_count > 5:
                raise forms.ValidationError("Не может быть больше 5 тегов")
            if len(tag) < 3 or len(tag) > 50 or not litnum_re.search(tag):
                raise forms.ValidationError("Tag's length must be beetwen 3 and 50 symbols and contain letters, numbers and underscores.")      		


PostImagesFormSet = inlineformset_factory(Post, PostImages, form=PostImagesForm, fields=('__all__'), extra=1, max_num=USEXT_FILES_COUNT_COMMON)
PostImagesFormSetVip = inlineformset_factory(Post, PostImages, form=PostImagesForm, fields=('__all__'), extra=1, max_num=USEXT_FILES_COUNT_VIP)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm

def post_detail(request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'blog/post_detail.html', {'post': post})

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})
	
def post_new(request):
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.published_date = timezone.now()
                post.save()
                return redirect('blog.views.post_detail', pk=post.pk)
        else:
            form = PostForm()
        return render(request, 'blog/post_edit.html', {'form': form})
		

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

diary/blog/views.py
from django.shortcuts import render, redirect
from .models import Post, PostImages, UUIDTaggedItem
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import PostForm, PostImagesFormSet, PostImagesFormSetVip
from django.contrib.auth.decorators import login_required
from usext.models import UserExtends
from django.utils import timezone
from django.db.models import Count
from taggit.models import Tag
from diary.settings import TAG_LIMIT, USEXT_TEXT_LENGTH_COMMON,USEXT_TEXT_LENGTH_VIP

def index(request):
    
    num_posts=Post.objects.all().count()
    num_images=PostImages.objects.all().count()

    return render(
        request,
        'index.html',
        context={'num_posts':num_posts,'num_images':num_images},
    )

def perm_denied(request):
    return render(request,'blog/perm_denied.html')

def tag_cloud(user):
    tag_cloud = Tag.objects.filter(id__in=UUIDTaggedItem.objects.values('tag').filter(object_id__in=Post.objects.filter(user=user)).annotate(dcount=Count('tag')).values('tag').order_by('-dcount')[:20])
    return tag_cloud

@login_required
def search_by_tag(request, tag):
    posts_with_tag = Post.objects.filter(user=request.user).filter(tags__name__in=[tag]).order_by('-post_date')
    t_cloud = tag_cloud(request.user) #Tag.objects.filter(id__in=UUIDTaggedItem.objects.values('tag').filter(object_id__in=Post.objects.filter(user=request.user)).annotate(dcount=Count('tag')).values('tag').order_by('-dcount')[:TAG_LIMIT])
    return render(request, 'blog/tags.html', {'posts_with_tag': posts_with_tag, 'search_tag':tag, 'tag_cloud':t_cloud})


@login_required
def search(request):
    if 'q' in request.GET and request.GET['q']:
        tag = request.GET['q']
        posts_with_tag = Post.objects.filter(user=request.user).filter(tags__name__in=[tag]).order_by('-post_date')
        t_cloud = tag_cloud(request.user)
        return render(request, 'blog/tags.html', {'posts_with_tag': posts_with_tag, 'search_tag':tag, 'tag_cloud':t_cloud})
    else:
        t_cloud = tag_cloud(request.user)
        return render(request, 'blog/tags.html', {'posts_with_tag': [], 'search_tag':'', 'tag_cloud':t_cloud})


class PostListView(LoginRequiredMixin, generic.ListView):
    model = Post
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by('-post_date')

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['tag_cloud'] = tag_cloud(self.request.user) #Tag.objects.filter(id__in=UUIDTaggedItem.objects.values('tag').filter(object_id__in=Post.objects.filter(user=self.request.user)).annotate(dcount=Count('tag')).values('tag').order_by('-dcount')[:TAG_LIMIT])
        return context

# class PostImagesListView(generic.ListView):
#     model = PostImages
#     def get_queryset(self):
#         return PostImages.objects.filter(post=self.request.post).order_by('order')


class PostDetailView(generic.DetailView):
    model = Post


class PostCreate(LoginRequiredMixin,CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        vip = UserExtends.objects.get(user=self.request.user).vip
        kwargs['vip'] = vip 
        if vip < timezone.now(): 
            kwargs['maxsymb'] = USEXT_TEXT_LENGTH_COMMON
        else:
            kwargs['maxsymb'] = USEXT_TEXT_LENGTH_VIP
        return kwargs

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        vip = UserExtends.objects.get(user=self.request.user).vip
        if vip < timezone.now():
            post_form = PostImagesFormSet()
        else:
            post_form = PostImagesFormSetVip()
        # post_form = PostImagesFormSet()
        return self.render_to_response(self.get_context_data(form=form,post_form=post_form))       

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        # print('*'*60)
        vip = UserExtends.objects.get(user=self.request.user).vip
        # print(vip)
        # print('*'*60)
        if vip < timezone.now():
            post_form = PostImagesFormSet(self.request.POST, self.request.FILES)
        else:
            post_form = PostImagesFormSetVip(self.request.POST, self.request.FILES)
        # post_form = PostImagesFormSet(self.request.POST, self.request.FILES)
        if (form.is_valid() and post_form.is_valid()):
            return self.form_valid(form, post_form)
        return self.render_to_response(self.get_context_data(form=form,post_form=post_form))       

    def form_valid(self, form, post_form):
        form.instance.user = self.request.user
        self.object = form.save()
        post_form.instance = self.object
        post_form.save()
        return redirect(self.success_url)



def user_permitted(function): 
    def _wrapped_view(request, *args, **kwargs): 
        obj = Post.objects.get(id = kwargs['pk'])
        if obj.user != request.user: 
            return redirect(reverse_lazy('perm-denied')) 
        return function(request, *args, **kwargs) 
    return _wrapped_view 



class PostUpdate(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        vip = UserExtends.objects.get(user=self.request.user).vip
        kwargs['vip'] = vip 
        if vip < timezone.now(): 
            kwargs['maxsymb'] = USEXT_TEXT_LENGTH_COMMON
        else:
            kwargs['maxsymb'] = USEXT_TEXT_LENGTH_VIP
        return kwargs

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        vip = UserExtends.objects.get(user=self.request.user).vip
        if vip < timezone.now():
            post_form = PostImagesFormSet(instance = self.object)
        else:
            post_form = PostImagesFormSetVip(instance = self.object)
        return self.render_to_response(self.get_context_data(form=form,post_form=post_form))       

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        vip = UserExtends.objects.get(user=self.request.user).vip
        if vip < timezone.now():
            post_form = PostImagesFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            post_form = PostImagesFormSetVip(self.request.POST, self.request.FILES, instance=self.object)
        # post_form = PostImagesFormSet(self.request.POST, self.request.FILES, instance=self.object)
        if (form.is_valid() and post_form.is_valid()):
            return self.form_valid(form, post_form)
        return self.render_to_response(self.get_context_data(form=form,post_form=post_form))       

    def form_valid(self, form, post_form):
        self.object = form.save()
        post_form.instance = self.object
        # print('41'*30)
        post_form.save()
        return redirect(self.success_url)    



class PostDelete(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('posts')
    # def get_queryset(self):
    #     base_queryset = super(PostUpdate, self).get_queryset()
    #     return base_queryset.filter(user = self.request.user)

mysite/blog/views.py
from django.shortcuts import render

# Create your views here.

diary/blog/templates/blog/perm_denied.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% include "account/blocks/start_block.html" %}
	<div class="section-title">
		<h2 class="title">{% trans 'Permission denided' %}</h2>
	</div>

	<p>{% trans 'You cant do this' %}</p>
{% include "account/blocks/end_block.html" %}
{% endblock %}

diary/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% include "account/blocks/start_block.html" %}
	<div class="section-title">
		<h2 class="title">{% trans 'Delete post' %}</h2>
	</div>

	<p>{% trans 'Are you sure you want to delete this post?' %}</p>

	<form action="" method="POST">
		{% csrf_token %}
		<div class="col-md-12">
			<div class="form-group common_center">
				<button class="primary-button">{% trans 'Yes, delete' %}</button>
			</div>
		</div>
	</form>
{% include "account/blocks/end_block.html" %}
{% endblock %}

diary/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load thumbnail %}

{% block additional_css %}
  <link rel="stylesheet" href="{% static 'lightbox/css/lightbox.css' %}" >
{% endblock %}
{% block content %}

<div id="post-header" class="page-header">

  {% if post.postimages_set.all|first %}
  {% with post.postimages_set.all|first as img %}
  <div class="page-header-bg" style="background-image: url({{ img.image.url }}); background-size: cover;" data-stellar-background-ratio="0.5"></div>
  {% endwith %}
  {% else %}
  <div class="page-header-bg" style="background-image: url({{ post.get_post_bg }}); background-size: cover;" data-stellar-background-ratio="0.5"></div>

  {% endif %}



  <div class="container">
    <div class="row">
      <div class="col-md-3">
        &nbsp;
      </div>
      <div class="col-md-6">
        <div class="post-category">
          {% for tag in post.tags.names %}  <a href="/t/{{ tag }}">{{ tag }}</a> {% endfor %}
        </div>
        <ul class="post-meta">
          <li>{{ post.post_date }}</li>
        </ul>
      </div>
      <div class="col-md-3">
        &nbsp;
      </div>
    </div>
  </div>
</div>

<!-- section -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <div class="col-md-3">
        &nbsp;
      </div>
      <div class="col-md-6">
        <!-- post share -->
        <div class="section-row">
          <div class="post-share">
            <a href="{% url 'post_update' pk=post.id %}" class="social-pinterest"><i class="fa fa-edit"></i><span>Edit</span></a>
            <a href="http://www.facebook.com/sharer.php?s=100&p[url]={{ post.get_absolute_url }}&p[title]=post on Socio&p[summary]='{{ post.text }}'&p[images][0]='{% if post.postimages_set.all|first %}
  {% with post.postimages_set.all|first as img %}
  {{ img.image.url }}
  {% endwith %}
  {% else %}
  {{ post.get_post_bg }}{% endif %}" onclick="window.open(this.href, this.title, 'toolbar=0, status=0, width=548, height=325'); return false;"



             class="social-facebook"><i class="fa fa-facebook"></i><span>Facebook</span></a>
            <a href="#" class="social-vk"><i class="fa fa-vk"></i><span>{% trans 'VK' %}</span></a>
            <input type="hidden" id="cont" value="">
          </div>
        </div>

        <div class="section-row">
          <div class="galery-widget"><ul>
            <div class="popup-gallery">
             {% for img in post.postimages_set.all %}
             <li><a href="{{ img.image.url }}" data-lightbox="roadtrip">
               {% thumbnail img.image "180x135" crop="center" as im %}
               <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="" >     

               {% endthumbnail  %}
             </a></li>
             {% endfor %}

           </div>
         </ul></div>
       </div>

       <div class="section-row common_min_height">
        <p>{{ post.text|linebreaks }}</p>
      </div>
      {% if user.is_authenticated and user == post.user %} 
      <div class="section-row">
        <div class="post-share">
          <a href="{% url 'post_update' pk=post.id %}" class="social-pinterest"><i class="fa fa-edit"></i><span>{% trans 'Edit post' %}</span></a>
          <a href="{% url 'post_delete' pk=post.id %}" ><i class="fa fa-trash"></i><span>{% trans 'Delete post' %}</span></a>
        </div>
      </div>
      {% endif %}
    </div>
    <div class="col-md-3">
      &nbsp;
    </div>
  </div>
</div>
</div>
{% endblock %}

{% block js %} 
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

  <!-- https://lokeshdhakar.com/projects/lightbox2 -->
  <script src="{% static 'lightbox/js/lightbox-plus-jquery.js' %}"></script>
  <script>
    lightbox.option({
      "albumLabel": "{% trans 'Image' %} %1 {% trans 'of' %} %2"
    })
</script>
{% endblock %}

diary/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
{% include "blog/blocks/start_block.html" %}  
   <div class="col-md-12"> 
    <div class="section-title">
        <h2 class="title">{% trans 'Заголовок Добавление/редактирование поста' %}</h2>
    </div>
  </div>

<div class="col-md-12"> 
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
</div>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}


  <div class="col-md-12">
    <div class="form-group">
        <textarea class="input min_height_textarea" name="text" cols="40" rows="10" maxlength="{{ form.maxsymb }}" required id="id_text" placeholder="{% trans 'Введите пост' %}">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
      <span class="text-success" id="result">0</span>/{{ form.maxsymb }}
    </div>
  </div>
  <div class="col-md-12">
    <div class="form-group">
      <span class="for_tags">
        {{ form.tags }}
      </span>
      <sub for="id_tags">{% trans 'Описание тегов' %}</sub>

    </div>
  </div>
  <br>
  {{ post_form.management_form }}

  <!-- {% for pform in post_form %}
      <div class="formset_row {{ post_form.prefix }}">          
          {% if forloop.last %}
              {{ pform }}
          {% else %}
              {% if pform.image.value %}
                  {% for hidden in pform.hidden_fields %}
                    {{ hidden }}
                  {% endfor %}
                  <input type="hidden" name="{{ post_form.prefix }}-{{ forloop.counter0}}-DELETE" id="id_{{ post_form.prefix }}-{{ forloop.counter0}}-DELETE">
                  <input type="number" name="{{ post_form.prefix }}-{{ forloop.counter0}}-order" id="id_{{ post_form.prefix }}-{{ forloop.counter0}}-order" value="{{ forloop.counter0}}">
                  <img src="{{ pform.image.value.url }}" alt="" style="width: 140px;">

              {% endif %}
          {% endif %}
      </div>
      {% endfor %} -->

      {% if post_form.count != 0 %}44{{post_form.count}}44
        {% for pform in post_form %}666
        <div class="formset_row {{ post_form.prefix }}">
          {% for hidden in pform.hidden_fields %}
            {{ hidden }}
          {% endfor %}                  
            
          <input type="hidden" name="{{ post_form.prefix }}-{{ forloop.counter0}}-DELETE" id="id_{{ post_form.prefix }}-{{ forloop.counter0}}-DELETE">
          <input type="number" name="{{ post_form.prefix }}-{{ forloop.counter0}}-order" id="id_{{ post_form.prefix }}-{{ forloop.counter0 }}-order" value="{{ forloop.counter0 }}">
          {% if pform.image.value %}
            <img src="{{ pform.image.value.url }}" alt="" style="width: 140px;">
          {% else %}
            <input type="file" name="{{ post_form.prefix }}-{{ forloop.counter0 }}-image" id="id_{{ post_form.prefix }}-{{ forloop.counter0 }}-image" >
          {% endif %}

        </div>
        {% endfor %}      
      {% else %} {{ pform }}

      {% endif %}




      <div class="col-md-12">
        <div class="form-group common_center">
          <button class="primary-button">{% trans 'Сохранить пост' %}</button>
        </div>
      </div>  

    </form>

    {% block js %} 


    {% endblock %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    <script>
      $(document).ready(function() {
        document.getElementById("id_tags").placeholder = "{% trans 'Enter tags here' %}";
        $('#result').html($('#id_text').val().length);

      }); 
      $('#id_text').bind('input', function(){
        $('#result').html($(this).val().length);
      });
    </script>
    <script type="text/javascript">
      $('.formset_row').formset({
        addText: 'add image',
        deleteText: 'remove image',
        prefix: '{{ post_form.prefix }}',
        keepFieldValues: ''
      });
    </script>

    {% include "blog/blocks/end_block.html" %}
    {% endblock %}

diary/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block page_style_css %}

{% endblock %}

{% block content %}
<div class="section">
  <!-- container -->
  <div class="container">
    <div class="row">

      <h1 class="title common_style">{% trans "All posts" %}</h1>


      {% if post_list %}
      {% for post in post_list %}
      {% cycle '<div class="display-inline-block">' '' '' %}
        {% include "blog/blocks/post_list_element.html" with post=post %}
      {% cycle '' '' '</div>' %}
      {% endfor %}
      {% else %}
      <p>Нет постов.</p>
      {% endif %}       
    </div>
  </div>
</div>
{% endblock %}

{% block tagCloud %}

<div class="section">
  <!-- container -->
  <div class="container">
    <div class="row">
      <div class="tagcloud01">
        <ul>
          {% for tag in tag_cloud %}
          <li><a href="/t/{{tag}}">{{tag}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

diary/blog/templates/blog/tag_cloud.html
{% extends "base.html" %}

{% block content %}
  <div class="section">
    <!-- container -->
    <div class="container">
    <div class="row">
      {% for tag in tag_cloud %}  
         {{ tag.name }} - {{ tag.dcount }}<br>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

diary/blog/templates/blog/tags.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <div class="section">
    <!-- container -->
    <div class="container">
    <div class="row">
    <h1 class="title common_style">{% trans 'Posts list by hashtag' %} #{{ search_tag }}</h1>

    {% if posts_with_tag %}
      {% for post in posts_with_tag %}
        {% cycle '<div class="display-inline-block">' '' '' %}
        {% include "blog/blocks/post_list_element.html" with post=post %}
        {% cycle '' '' '</div>' %}
      {% endfor %}
    {% else %}
      <p>{% trans 'No posts' %}.</p>
    {% endif %}       
    </div>
  </div>
</div>
{% endblock %}

{% block tagCloud %}

<div class="section">
  <!-- container -->
  <div class="container">
    <div class="row">
      <div class="tagcloud01">
        <ul>
          {% for tag in tag_cloud %}
          <li><a href="/t/{{tag}}">{{tag}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}